#!/usr/bin/env bash
#This is a script that does displays the time for 12 hours and 59 minutes:

hr=0

while [ $hr -le 12 ]
do
	echo "Hour: $hr"
	minute=1
	while [ $minute -le 59 ]
	do
		echo "$minute"
		(( minute++ ))
	done
	(( hr++ ))
done
